# Generated by Django 4.1.1 on 2023-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='addresse',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
