# Generated by Django 4.1.1 on 2023-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entreprise_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
