# Generated by Django 4.1.1 on 2023-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entreprise_telephone_etudiant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
