# Generated by Django 4.1.1 on 2023-02-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='telephone',
        ),
    ]
