# Generated by Django 4.1.1 on 2023-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_forum_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='contenu',
            field=models.TextField(),
        ),
    ]
