# Generated by Django 4.1.1 on 2023-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_forum_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(default='my commment'),
            preserve_default=False,
        ),
    ]
