# Generated by Django 4.1.1 on 2023-02-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_commentaire_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='app.forum'),
            preserve_default=False,
        ),
    ]
