# Generated by Django 4.1.1 on 2023-02-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_commentaire_commentateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='commentaire',
            new_name='contenu',
        ),
    ]
