# Generated by Django 4.1.1 on 2023-02-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_commentaire_commentaire_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entro', to='app.entreprise'),
        ),
    ]
