# Generated by Django 4.1.1 on 2023-02-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_emailentreprise_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='forum',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenu', to='app.etudiant'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='app.etudiant'),
        ),
    ]
