# Generated by Django 4.1.1 on 2023-02-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_commentaire_forum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='app.forum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='app.etudiant'),
        ),
    ]
