# Generated by Django 4.1.1 on 2023-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_passwordentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='phone',
            field=models.CharField(default='033333', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
